#!/bin/bash
docker stop composetest_phpmyadminMaster_1
docker stop composetest_phpmyadminSlave1_1
docker stop composetest_phpmyadminSlave2_1
docker stop composetest_phpmyadminSlave3_1
docker stop composetest_phpmyadminSlave4_1
docker stop composetest_db_master_1 
docker stop composetest_db_slave1_1 
docker stop composetest_db_slave2_1 
docker stop composetest_db_slave3_1 
docker stop composetest_db_slave4_1 


cd /home/rado/Programowanie/Skrypty
./serwerownia-out

